"""Renderer-neutral multiscale chunk planning and streaming."""

from .chunks import (
    ChunkGrid,
    chunk_boundaries,
    chunk_ids_in_region,
    chunk_key_id,
    chunk_shape_for,
    chunk_sizes_for,
    chunk_slices_for,
    normalize_chunk_sizes,
    regular_chunk_sizes,
)
from .composition import fill_unloaded_chunks, nearest_resample_region
from .diagnostics import LevelDiagnosticArray, PlanComparison, PlanTrace
from .geometry import (
    anisotropic_extent_for_bytes,
    clamp_region_to_budget,
    expand_region_to_chunk_grid,
    isotropic_extent_for_bytes,
    native_chunks_in_region,
)
from .model import (
    ChunkEvent,
    ChunkState,
    InteractionState,
    Layout,
    Level,
    Plan,
    PlanCoverage,
    PlanDelta,
    Pyramid,
    Region,
    Status,
    StreamDiagnostics,
    Tile,
    TileKey,
    Update,
    View,
    identity_transform,
)
from .planner import (
    Planner,
    available_tile_keys,
    merge_plans,
    plan_from_slices,
)
from .resident import (
    ResidentArrays,
    ResidentChange,
    ResidentLease,
    ResidentTransition,
    ResidentWindow,
)
from .runtime import Runtime
from .source import Source
from .stream import Stream
from .target import PassTarget, PhaseTarget, ResidencyLease, StagingTarget, Target
from .virtual import MultiScaleVirtualData, VirtualArrayView, VirtualData

__all__ = [
    "ChunkEvent",
    "ChunkGrid",
    "ChunkState",
    "InteractionState",
    "Layout",
    "Level",
    "LevelDiagnosticArray",
    "MultiScaleVirtualData",
    "PassTarget",
    "PhaseTarget",
    "Plan",
    "PlanComparison",
    "PlanCoverage",
    "PlanDelta",
    "PlanTrace",
    "Planner",
    "Pyramid",
    "Region",
    "ResidencyLease",
    "ResidentArrays",
    "ResidentChange",
    "ResidentLease",
    "ResidentTransition",
    "ResidentWindow",
    "Runtime",
    "Source",
    "StagingTarget",
    "Status",
    "Stream",
    "StreamDiagnostics",
    "Target",
    "Tile",
    "TileKey",
    "Update",
    "View",
    "VirtualArrayView",
    "VirtualData",
    "anisotropic_extent_for_bytes",
    "available_tile_keys",
    "chunk_boundaries",
    "chunk_ids_in_region",
    "chunk_key_id",
    "chunk_shape_for",
    "chunk_sizes_for",
    "chunk_slices_for",
    "clamp_region_to_budget",
    "expand_region_to_chunk_grid",
    "fill_unloaded_chunks",
    "identity_transform",
    "isotropic_extent_for_bytes",
    "merge_plans",
    "native_chunks_in_region",
    "nearest_resample_region",
    "normalize_chunk_sizes",
    "plan_from_slices",
    "regular_chunk_sizes",
]
